script:
  - ./build $TRAVIS_OS_NAME
jobs:
  include:
    - stage: build
      os: linux
      workspaces:
        create:
          name: shared
    - stage: python
      dist: xenial
      language: python
      sudo: required
      python:
        - '3.6'
        - '3.7'
        - '3.8'
      workspaces:
        use: shared
        before_install:
          - pip3 install -U pip
        install:
          - pip install -e .[test]
        script:
          - pytest --cov-report term --cov=./src
        after_success:
          - coverage run --branch --source=src/ -m pytest tests/
          - bash <(curl -s https://codecov.io/bash)
          - coveralls






dist: xenial
language: python
sudo: required
python:
  - '3.6'
  - '3.7'
  - '3.8'
before_install:
  - pip3 install -U pip
install:
  - pip install -e .[test]
script:
  - pytest --cov-report term --cov=./src
after_success:
  - coverage run --branch --source=src/ -m pytest tests/
  - bash <(curl -s https://codecov.io/bash)
  - coveralls