dist: xenial
language: python
sudo: required
python:
  - '3.6'
  - '3.7'
  - '3.8'
before_install:
  - python --version
  - pip3 install -U pip
  - pip3 install -U pytest
install:
  - pip install -e .[test]
script:
  - pytest --cov=./src
after_success:
  - coverage run --branch --source=src/ -m pytest tests/
  - bash <(curl -s https://codecov.io/bash)
  - coveralls